server:
  port: 8443
  http-port: 8080
  servlet:
    context-path: /qmplatform
  ssl:
    enabled: true
    key-alias: tomcat_https
    key-store: classpath:tomcat_https.keystore
    key-password: 123456
    key-store-password: charon
    key-store-type: JKS
  max-http-request-header-size: 1024KB

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  profiles:
    active: @spring.profiles.active@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 3000

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/**/*Mapper.xml

# 分页插件
pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 自定义属性
custom:
  database: qmplatform_single
  packing: @packaging@
  # 数据库是否docker环境
  dbIsDocker: false

