spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/${custom.database}
    username: postgres
    password: ENC(D9fe9pzb1/BZ7cdXkAV4tyO8I+WJqKvR)
  mail:
    username: your_mail_addr@163.com
    password: ENC(your_enc_password)
